<a href="https://colab.research.google.com/github/Archiezarc/Remainders-with-face-recognition-/blob/main/CSIT553_class1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# only run once
!git clone https://github.com/profliuhao/CSIT553.git

Cloning into 'CSIT553'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 145 (delta 58), reused 50 (delta 11), pack-reused 0 (from 0)
Receiving objects: 100% (145/145), 4.34 MiB | 9.25 MiB/s, done.
Resolving deltas: 100% (58/58), done.


# CSIT 553 Class 1 Eexercise: Numpy


### Instruction
Load the data **iris.data** and create a 2d-array called *iris* to store the first four columns (sepallenght, sepalwidth, petallength, petalwidth).

Each row represents the data of one sample.


In [3]:
import numpy as np

# file = 'iris.data'/
file = '/content/CSIT553/Module_1/CSIT553_class1_exercise/iris.data'
iris = np.genfromtxt(file, delimiter=',')
iris = iris[:,:4]
#names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [4]:
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## Exercise 1

How many samples are recorded? In other words, how many rows is in the array **iris**?

In [5]:
# You should write your answer within this cell
# write your code of exercise 1 here
iris.shape[0]


150

## Exercise 2
What is the mean value of each feature?

In [6]:
# You should write your answer within this cell
# write your code of exercise 2 here

np.mean(iris,axis=0)

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

### Exercise 3
Find the samples with sepal length larger than 5 and sepal width smaller than 3.

In [9]:
# You should write your answer within this cell
# write your code of exercise 3 here
sl_arr = iris[:, 0]
sw_arr = iris[:, 1]
selected_boolean = (sl_arr > 5) & (sw_arr < 3)
selected_boolean


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True, False, False,  True,  True,  True, False,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False, False, False,  True, False,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
        True, False,  True, False,  True, False, False, False,  True,
        True, False, False,  True, False,  True,  True, False, False,
       False,  True,  True, False,  True,  True,  True, False, False,
        True, False,

## Exercise 4
What is the correlation between petal length and petal width?

### Hint
The function **corrcoef** in Numpy return Pearson product-moment correlation coefficients.

If you want to get the Pearson correlation coefficients between the variables in **xarr** and **yarr**, you can execute the command:

np.corrcoef(xarr, yarr)

In [10]:
# You should write your answer within this cell
# write your code of exercise 4 here
pl_arr = iris[:, 2]
pw_arr = iris[:, 3]
np.corrcoef(pl_arr,pw_arr)


array([[1.       , 0.9627571],
       [0.9627571, 1.       ]])